version: "3.5"

networks:
  net-spring-circuit-breaker:
    driver: bridge

services:
  psql-products:
    image: postgres:13.3-alpine
    container_name: "psql-products"
    hostname: psql-products
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: mcproducts
      POSTGRES_PASSWORD: mcproducts
      POSTGRES_DB: mcproducts
    networks:
      net-spring-circuit-breaker:

  psql-assessments:
    image: postgres:13.3-alpine
    container_name: "psql-assessments"
    hostname: psql-assessments
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: mcassessments
      POSTGRES_PASSWORD: mcassessments
      POSTGRES_DB: mcassessments
    networks:
      net-spring-circuit-breaker:

  # Jeager
  jaeger:
    image: jaegertracing/all-in-one:latest
    command: ["--query.max-clock-skew-adjustment=1s"]
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      net-spring-circuit-breaker:
  
  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      net-spring-circuit-breaker:
  
  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      net-spring-circuit-breaker:
  
  # OTEL Collector
  # otel-collector:
  #   image: otel/opentelemetry-collector:0.73.0
  #   command: [ "--config=/etc/otel-collector-config.yaml" ]
  #   volumes:
  #     - ./opentelemetry/otel-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "1888:1888"   # pprof extension
  #     - "13133:13133" # health_check extension
  #     - "4317:4317"   # OTLP gRPC receiver
  #     - "55670:55679" # zpages extension
  #   depends_on:
  #     - jaeger-all-in-one
  #     - zipkin-all-in-one
  #   networks:
  #     net-spring-circuit-breaker:

  otel-collector-contrib:
    image: otel/opentelemetry-collector-contrib:0.70.0
    restart: unless-stopped
    command:
      - --config=/etc/otelcol-config.yml
    volumes:
      - ./opentelemetry/otel-contrib-config.yaml:/etc/otelcol-config.yml
    ports:
      - "1777:1777"   # pprof extension
      - "55679:55679" # zPages extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - loki
    networks:
      net-spring-circuit-breaker:
  
  # Loki
  loki:
    image: grafana/loki
    container_name: loki
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    ports:
      - 3100:3100
    depends_on:
      - grafana
    networks:
      net-spring-circuit-breaker:
  
  # Grafana
  grafana:
    image: grafana/grafana
    user: "root:root"
    container_name: grafana
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      net-spring-circuit-breaker:
